version: '3.8'

services:
  mp3-downloader:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mp3-network

volumes:
  downloads:
  logs:

networks:
  mp3-network:
    driver: bridge